/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

// Headers definitions:

void init_gpio(void);
void init_tim3(void);

int main(void)
{
    // Configurar el hardware antes de la función principal
    init_gpio(); // Configuración de los pines GPIO
    init_tim3(); // Configuración del temporizador TIM3

    /* Loop forever */
	while (1)
    {
        // Application code here
    }
}

/**/
void init_gpio(void){
    // Encender la señal de reloj para el GPIOA
    RCC->AHB1ENR |= (1<<0);
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN_Msk; // Encender la señal de reloj para el GPIOA

    // RCC: Nombre del periférico que controla el reloj de los GPIOs
    // AHB1: Bus de alta velocidad 1
    // ENR: Registro de habilitación de reloj
    // GPIOAEN: Bit que habilita el reloj para el GPIOA, y este es el PIN que se va a utilizar
    // Msk: Máscara de bits para el pin GPIOAEN

    /**/ 

    // Configurar el pin PA5 como salida push-pull
    GPIOA->MODER &= ~(0b11 << GPIO_MODER_MODE5_Pos); // Limpiar los bits de modo del pin PA5; limpiar la posición
    GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos); // 01 para que sea de propósito general (GPIO), PA5 como salida

    GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5); // Configurar el pin PA5 como salida push-pull

    GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos); // Limpiar los bits de velocidad del pin PA5
    GPIOA->OSPEEDR |= (0b01 << GPIO_OSPEEDR_OSPEED5_Pos); // Configurar el pin PA5 con velocidad media

    GPIOA->PUPDR &= ~(0b11 << GPIO_PUPDR_PUPD5_Pos); // Limpiar los bits, deactivamos el pull-up y pull-down
    
    GPIOA->ODR |= (GPIO_ODR_OD5); // Encender el LED en el pin PA5
}

/*
Configurar el temporizador TIM3 para generar una interrupción cada 0.25 segundos
*/

void init_tim3(void){

    // Encender la señal de reloj para el TIM3
    RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // Encender la señal de reloj 

    // Configuración del TIM3

    TIM3->CNT = 0; // Inicializar el contador del TIM3 a 0
    TIM3->PSC = (1600- 1); // Para incrementar el CNT cada 0.1 us
    TIM3->ARR = (2500 - 1); // Para generar una interrupción cada 0.25 segundos

    TIM3->CR1 &= ~(0b11 << TIM_CR1_CKD_Pos); // Limpia; la señal de 16MHz pasa sin cambios
    TIM3->CR1 |= (TIM_CR1_ARPE); // Se activa el preload del ARR
    TIM3->CR1 &= ~(TIM_CR1_DIR_Pos); // Limpia, configura el contador para que cuente hacia arriba

    TIM3->DIER |= (TIM_DIER_UIE); // Activar la interrupción por evento de actualización (Update Interrupt Enable)

    NVIC_EnableIRQ(TIM3_IRQn); // Registrar la interrupción del TIM3 en el NVIC (Nested Vectored Interrupt Controller)

    // Activar el contador - to-do

    TIM3->CR1 |= TIM_CR1_CEN; // Activar el contador del TIM3, permitir que se incremente


}

// Esta función de abajo no está en los headers porque es una función de interrupción, y no se llama directamente desde el main.c, sino que se ejecuta cuando ocurre la interrupción del TIM3

void TIM3_IRQHandler(void){

    // Verificar que la bandera está en alto

    if(TIM3->SR && TIM_SR_UIF){} 
        TIM3->SR &= ~TIM_SR_UIF; // Bajando la bandera de interrupción

        // Hacemos 'algo' en la interrupción, por ejemplo, cambiar el estado del pin PA5 (toggle)
        GPIOA->ODR ^= (GPIO_ODR_OD5); // Cambiar el estado del pin PA5 (toggle)

} // Con esto garantizamos que el nombre del vector de interrupciones sea igual al de la función que se ejecutará cuando ocurra la interrupción del TIM3